Workaround for host.docker.get_containers() failure
The `userns_remap` test failed with the following output:

```text
============================= test session starts ==============================
  platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
  rootdir: /home/runner
  plugins: mock-3.6.1, xdist-2.4.0, forked-1.3.0, cov-3.0.0, verbose-parametrize-1.7.0, testinfra-6.4.0, plus-0.2, metadata-1.11.0, html-3.1.1
  collected 1 item

  molecule/userns_remap/tests/test_default.py F                            [100%]

  =================================== FAILURES ===================================
  ____________________ test_run_container[ansible://instance] ____________________

  host = <testinfra.host.Host ansible://instance>

      def test_run_container(host):
          subuid_entry = _get_entry(host, Path("/etc/subuid"), "dockremap")
          assert subuid_entry is not None

          subgid_entry = _get_entry(host, Path("/etc/subgid"), "dockremap")
          assert subgid_entry is not None

          subuid = subuid_entry[1]
          subgid = subgid_entry[1]
          docker_dir_path = Path("/var/lib/docker/{}.{}".format(subuid, subgid))
          assert host.file(str(docker_dir_path)).is_directory

          args = (
              "docker", "container", "run",
              "--name=say-hello",
              "hello-world",
          )
          cmd = host.run_test(command=" ".join(args))
          assert "Hello from Docker!" in cmd.stdout

  >       matches = host.docker.get_containers(name="say-hello")

  molecule/userns_remap/tests/test_default.py:31:
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/testinfra/modules/docker.py:115: in get_containers
      for docker_id in cls(None).check_output(cmd, *args).splitlines():
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/testinfra/modules/base.py:49: in check_output
      return cls._host.check_output(*args, **kwargs)
  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/testinfra/host.py:75: in run
      return self.backend.run(command, *args, **kwargs)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  self = <testinfra.backend.ansible.AnsibleBackend object at 0x7ff176422280>
  command = "docker ps --all --quiet --format '{{.Names}}' --filter name=say-hello"
  args = ('name', 'say-hello'), kwargs = {}, host = None
  out = {'msg': "template error while templating string: unexpected '.'. String: docker ps --all --quiet --format '{{.Names}}' --filter name=say-hello"}

      def run(self, command, *args, **kwargs):
          command = self.get_command(command, *args)
          if not self.force_ansible:
              host = self.ansible_runner.get_host(
                  self.host,
                  ssh_config=self.ssh_config,
                  ssh_identity_file=self.ssh_identity_file,
              )
              if host is not None:
                  return host.run(command)
          out = self.run_ansible("shell", module_args=command, check=False)
          return self.result(
  >           out["rc"],
              command,
              stdout_bytes=None,
              stderr_bytes=None,
              stdout=out["stdout"],
              stderr=out["stderr"],
          )
  E       KeyError: 'rc'

  /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/testinfra/backend/ansible.py:59: KeyError
  =========================== short test summary info ============================
  FAILED molecule/userns_remap/tests/test_default.py::test_run_container[ansible:/instance]
  ============================== 1 failed in 16.40s ==============================
```

It seems that under the hood `get_containers()` executes something like this:

```sh
ansible -m shell -a "docker ps --all --quiet --format '{{.Names}}' --filter name=say-hello" ${pattern}
```

The `shell` module arguments are preprocessed by Jinja. The `{{.Names}}` format
string is mistakenly treated as template variable and expanded. This results in
the error.

As a workaround `docker inspect` is called directly from test code.